### ISSUE TITLE
Proposal for WASM.Simd

### ISSUE THREAD

**Issue by arunetm-zz** [stoklund/portable-simd#2]
Hi @stoklund, Are there any plans to bring this proposal to the attention of the WASM community through WASM/design repo? 

With WASM browser preview over, now is a good time to have proposals for post mvp features including WASM.Simd. Since you already had created this proposal, I was wondering if this can be used as a basis for initiating the discussions.

**Comment by stoklund** [comment]
It is my impression that most implementer prefer a single `v128` type in the WebAssembly mapping, so I'll simplify the mapping proposal to do that before presenting it to the community.

This would mean that the WebAssembly types become the same as the types used in the portable spec.

**Comment by arunetm-zz** [comment]
Yes, having a single v128 wasm type followed by an immediate in the encoding should help to keep the  simd types and ops better organized. It makes sense to have these discussions in the community to iron out more details into the encoding and design. 
Thanks for this work. Looking forward to your proposal.

**Comment by arunetm-zz** [comment]
Thanks for taking care of this.  https://github.com/WebAssembly/simd
